### ISSUE TITLE
More visible MARK sections

### ISSUE THREAD

**Issue by marcelmika** [iflix-letsplay/swift-style-guide#10]
This might be a little bit controversial, however, I already used it across many projects and it works quite nicely. I like to structure classes (especially ViewControllers) with MARK - sections. We all probably do. The thing is that another comment within large class is simply not visible enough:

![screen shot 2017-02-07 at 09 56 12](https://cloud.githubusercontent.com/assets/3537470/22684299/128c8e36-ed1c-11e6-8ae4-9a03de25ed9e.png)

Yes, you can always use the drop down to see all the functions nicely structured but what if we add some dividers to the code?

![screen shot 2017-02-07 at 09 55 45](https://cloud.githubusercontent.com/assets/3537470/22684357/47dffff0-ed1c-11e6-9d2e-10e66bdedd5e.png)

I think this small addition tremendously improves the code readability. Also, it is quite easy to add it as a snippet:

```
// -------------------------------------------------------------------------------
// MARK: - <#Section name#>
// -------------------------------------------------------------------------------
```
so at the end if you just type MARK XCode does all the work for you:

![screen shot 2017-02-07 at 10 04 59](https://cloud.githubusercontent.com/assets/3537470/22684592/3faa9ac4-ed1d-11e6-8b57-9ce8c1476e11.png)

**Comment by borisBarac** [comment]
i just had i thought maybe:
`// MARK - MARK BLOCK --------------------------------------------------------------------`
Gonna be visible the same, but gonna take less space?

**Comment by marcelmika** [comment]
@borisBarac yep, makes sense, two lines just for dashes might be to much. Although, the one liner would be enough, the *MARK BLOCK* part has dynamic size so each section will need to have different number of dashes to make the sections nicely aligned. So let's do two liner? 

```
// MARK: - <#Section name#>
// -------------------------------------------------------------------------------
```

**Comment by borisBarac** [comment]
LIKE IT :)

**Comment by mokagio** [comment]
Nice proposal @marcelmika 😄 .

I loved using `#pragma mark` in ObjC, but I now prefer to use extension to separate group of methods that are related to the same context. Although this has some disadvantages when it comet to the access level of properties and methods, some things that might stay private need to be made internal, etc.

I'm super happy to adopt the convention though, if the team likes it :). As usual you'll find individual comments below, please 👍 the one you'd like to go for team 😄 .

**Comment by mokagio** [comment]
Keep using `// MARK: - Section`.

**Comment by mokagio** [comment]
Use:

```
// MARK: - <#Section name#>
// -------------------------------------------------------------------------------
```

**Comment by mokagio** [comment]
Use:

```
// -------------------------------------------------------------------------------
// MARK: - <#Section name#>
```

**Comment by mokagio** [comment]
Use:

```
// -------------------------------------------------------------------------------
// MARK: - <#Section name#>
// -------------------------------------------------------------------------------
```

**Comment by nhisyam** [comment]
One thing I dislike about `------------------------------------`, each of us might have different window config (I use two editors laid vertically to each other.) is that it will go next line
```
------------------------------------
--------------------------------
```

Preferred `// MARK: - Section` approach.

**Comment by ghost** [comment]
I am up for this
```
// -------------------------------------------------------------------------------
// MARK: - <#Section name#>
// -------------------------------------------------------------------------------
```

**Comment by mokagio** [comment]
On 2017/03/03 the `// MARK:- Section` front was winning 7 to 3.

Closing the issue. No styleguide update is required, because that's already the suggested approach.

<img width="871" alt="screen shot 2017-03-03 at 3 56 56 pm" src="https://cloud.githubusercontent.com/assets/1218433/23538804/3812b542-002a-11e7-9d65-372f8a427ed3.png">
