### ISSUE TITLE
private vs fileprivate

### ISSUE THREAD

**Issue by mokagio** [iflix-letsplay/swift-style-guide#4]
The Swift migrator converted everything to `fileprivate` but that is not always the best choice.

![](https://pbs.twimg.com/media/CtjCP7HWIAA37kK.jpg)
_- via [Twitter](https://twitter.com/kaishin/status/781588125944520709)

My opinion is that we should always use `private`, and only resolve to `fileprivate` when we need the "private but visible in the file" access control, which is rarely the case.

More here: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html

Shall we make this a rule?

**Comment by mokagio** [comment]
_Shall we make this a rule?_ Yes

**Comment by mokagio** [comment]
_Shall we make this a rule?_ No

**Comment by cuteiosdev** [comment]
How does this effect the case where we have a single class with multiple extensions in a class? We're doing this in some instances. Do we need to use fileprivate or can we get away with private?

**Comment by mokagio** [comment]
In reply to @mattdelves question:

> How does this effect the case where we have a single class with multiple extensions in a class? [...] Do we need to use fileprivate or can we get away with private?

I would say that we can tweak the rule from:

> always use private, and only resolve to fileprivate when we need the "private but visible in the file" access control

to:

> always use private, and only resolve to fileprivate if the code wouldn't compile otherwise, which should only happen when the behaviour of "private to the outside world, but visible in extensions or other types defined in the same file".
