### ISSUE TITLE
Commas on new lines?

### ISSUE THREAD

**Issue by mokagio** [iflix-letsplay/swift-style-guide#7]
_Not sure who suggested this but I had a note about it._

This is the idea:

```
let longList = [
  "foo"
  , "bar"
  , "baz"
]
```

It looks quite awkward, but it's handy when it comes to diffs, in fact

```diff
# normal diff
let a = [
  w,
  x,
-  y
+ y,
+ z
]

# nicer diff
let a = [
  w
  , x
  , y
+ , z
]
```

Thoughts?  ¯\_(ツ)_/¯

**Comment by TimKregerIflix** [comment]
I'd find it very hard to adjust to that I think

**Comment by cuteiosdev** [comment]
nope.gif

I understand the benefit of a nicer diff, though it just rubs me the wrong way. Then again Haskell uses the comma at the start of the line so /shrug.

**Comment by SomeoneWeird** [comment]
https://github.com/apple/swift-evolution/blob/master/proposals/0084-trailing-commas.md

Looks like this was rejected too :(

**Comment by mokagio** [comment]
Fair enough. I'll close this 👍 .

![](https://cdn.meme.am/cache/instances/folder121/43924121.jpg)
